---
#.-----.---.-.--------.-----.-----.-----.---.-.----.-----.
#|     |  _  |        |  -__|__ --|  _  |  _  |  __|  -__|
#|__|__|___._|__|__|__|_____|_____|   __|___._|____|_____|
#                                 |__|

apiVersion: v1
kind: Namespace
metadata:
  name: f1-dash
